pipelines:
  compile:
    group: contacts-app
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ckaushik/contacts-ui.git
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              tasks:
                - exec: # indicates type of task
                   command: bash
                   arguments:
                     - "-c"
                     - "yarn install --production && yarn build"
              artifacts:
                - build:
                    source: build
              resources:
                - yarn
  package:
    group: contacts-app
    materials:
      compilation:
        pipeline: compile
        stage: build
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ckaushik/contacts-ui.git
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              tasks:
                - fetch:
                   pipeline: compile
                   stage: build
                   job: build
                   source: build
                - exec: # indicates type of task
                   command: bash
                   arguments:
                     - "-c"
                     - "docker build -t contacts-ui:${GO_PIPELINE_LABEL} -f Dockerfile.build ."
                - exec: # indicates type of task
                   command: bash
                   arguments:
                     - "-c"
                     - "echo contacts-ui:${GO_PIPELINE_LABEL} > contacts-ui-version.txt"
              artifacts:
                - build:
                    source: contacts-ui-version.txt
              resources:
                - docker
