pipelines:
  integration:
    group: contacts-app
    materials:
      frontend:
        pipeline: frontend-package
        stage: publish
      api:
        pipeline: api-package
        stage: publish
      mygit:
        git: https://github.com/ckaushik/contacts-ui.git
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                   command: bash
                   arguments:
                     - "-c"
                     - "docker build -t contacts-ui:${GO_PIPELINE_LABEL} -f Dockerfile.build ."
              resources:
                - deployer
