version: '2'
services:
  go-server:
    image: gocd/gocd-server:v17.10.0
    ports:
      - '8153:8153'
      - '8154:8154'
    volumes:
      - ./server_home:/godata

  go-agent-yarn:
    build:
      context: .
      dockerfile: 'Dockerfile.go-agent-yarn'
    depends_on:
      - go-server
    environment:
      AGENT_AUTO_REGISTER_KEY: '402d5e4d-4e72-4014-aa49-cca107d1bf3d'
      AGENT_AUTO_REGISTER_RESOURCES: yarn
      GO_SERVER_URL: https://go-server:8154/go

  go-agent-docker:
    build:
      context: .
      dockerfile: 'Dockerfile.go-agent-docker'
    depends_on:
      - go-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./files/go-agent/docker-config.json:/home/go/.docker/config.json
    environment:
      AGENT_AUTO_REGISTER_KEY: '402d5e4d-4e72-4014-aa49-cca107d1bf3d'
      AGENT_AUTO_REGISTER_RESOURCES: docker
      GO_SERVER_URL: https://go-server:8154/go
